-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "markdown", "mdx", "rmd", "quarto" },
--   callback = function()
--     vim.opt_local.conceallevel = 2
--     vim.opt_local.concealcursor = "nc"
--     vim.opt_local.wrap = true
--   end,
-- })
