[git_branch]
symbol = "🌳 "

[character]
# Change the symbol for the terminal prompt when the last command failed
error_symbol = '[✖](bold red)'

[dotnet]
disabled = true

[nodejs]
disabled = true

[elm]
disabled = true

[lua]
disabled = true

[package]
disabled = true

[swift]
disabled = true
