[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "jq" ]
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "just" ]
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "dotnet" ]
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "npm (install|info|i|remove|rm|uninstall) " ]
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "cat", "grep" ]
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "mkdir" ]
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "cat", "head" ]
modes = [ "autoEdit", "yolo" ]
