# Allow jj commands that don't require a pager
[[rule]]
toolName = "run_shell_command"
commandRegex = "jj (describe|split|bookmark|workspace|new)"
decision = "allow"
allowRedirection = true
priority = 100

# Allow these jj commands ONLY if they include the --no-pager flag
[[rule]]
toolName = "run_shell_command"
commandRegex = 'jj (show|log|diff|file show|help|resolve|status|st ).*--no-pager'
decision = "allow"
allowRedirection = true
priority = 100

# Deny jj show, log, and diff if they lack the --no-pager flag
[[rule]]
toolName = "run_shell_command"
commandPrefix = ["jj show", "jj log", "jj diff", "jj file show", "jj help", "jj resolve", "jj st", "jj status"]
decision = "deny"
priority = 90
denyMessage = "For stability, you must include the '--no-pager' flag when running that jj command."

# DijonBot MCP
[[rule]]
decision = "allow"
priority = 100
toolName = "list_pull_request_files"
mcpName = "dijon-github-bot"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "start_review"
mcpName = "dijon-github-bot"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "add_review_comment"
mcpName = "dijon-github-bot"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "submit_review"
mcpName = "dijon-github-bot"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "get_pull_request"
mcpName = "dijon-github-bot"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "create_review"
mcpName = "dijon-github-bot"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "create_issue"
mcpName = "dijon-github-bot"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "enter_plan_mode"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "find_organizations"
mcpName = "sentry"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "get_sentry_resource"
mcpName = "sentry"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "update_issue"
mcpName = "sentry"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "search_issues"
mcpName = "sentry"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "find_projects"
mcpName = "sentry"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "search_events"
mcpName = "sentry"
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "run_shell_command"
commandPrefix = [ "luacheck" ]
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "run_shell_command"
commandPrefix = [ "zizmor" ]
modes = [ "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 100
toolName = "run_shell_command"
commandPrefix = [ "date" ]
modes = [ "autoEdit", "yolo" ]
