symbolPreset: nerd
theme: 
  dark: dark-monokai
setupVersion: 1
modelRoles: 
  smol: high-charity/humanizer
  advisor: high-charity/qwen-qwythos
  task: high-charity/qwen-instruct:off
  plan: openrouter/google/gemini-3.6-flash
  default: openrouter/deepseek/deepseek-v4-flash
  slow: high-charity/qwen-mox
  vision: openrouter/google/gemma-4-26b-a4b-it
  tiny: high-charity/qwen-smol:off
statusLine: 
  preset: compact
  separator: none
  sessionAccent: true
terminal: 
  showProgress: true
display: 
  shimmer: disabled
personality: default
loop: 
  mode: prompt
tools: 
  approvalMode: yolo
completion: 
  notify: "off"
recap: 
  enabled: true
stt: 
  modelName: parakeet
startup: 
  quiet: false
  checkUpdate: false
collapseChangelog: true
power: 
  sleepPrevention: "off"
git: 
  enabled: false
memory: 
  backend: mnemopi
edit: 
  mode: replace
readLineNumbers: true
inspect_image: 
  enabled: true
todo: 
  remindersMax: 5
providers: 
  image: auto
  autoThinkingModel: lfm2-1.2b
  webSearch: auto
  fetch: auto
  tinyModel: lfm2-350m
  tinyModelDevice: default
  unexpectedStopModel: online
  openrouterVariant: default
  memoryModel: lfm2-1.2b
exa: 
  enabled: true
secrets: 
  enabled: true
commands: 
  enableClaudeUser: false
  enableClaudeProject: false
hideThinkingBlock: false
defaultThinkingLevel: auto
omitThinking: false
advisor: 
  enabled: false
  subagents: false
  syncBacklog: "off"
lsp: 
  diagnosticsOnEdit: true
web_search: 
  enabled: true
mcp: 
  notifications: false
  enableProjectConfig: true
disabledExtensions: 
  - context-file:user:GEMINI.md
skills: 
  enableSkillCommands: false
steeringMode: one-at-a-time
followUpMode: one-at-a-time
doubleEscapeAction: tree
emojiAutocomplete: false
compaction: 
  handoffSaveToDisk: true
bashInterceptor: 
  enabled: true
eval: 
  jl: true
browser: 
  enabled: false
tasks: 
  todoClearDelay: 60
tts: 
  localModel: kokoro
  localVoice: af_heart
speech: 
  mode: yield
  enabled: false
  voice: af_heart
provider: 
  appendOnlyContext: auto
tier: 
  advisor: none
task: 
  agentModelOverrides: 
    {}
  disabledAgents: 
    []
cycleOrder: 
  - default
  - slow
  - smol
  - tiny
retry: 
  fallbackChains: 
    plan: 
      - high-charity/qwen-mox
    default: 
      - high-charity/qwen-mox
model: 
  loopGuard: 
    checkAssistantContent: true
modelRoleStorage: global
prewalk: 
  enabled: false
treeFilterMode: default
features: 
  unexpectedStopDetection: true
mnemopi: 
  llmMode: smol
astGrep: 
  enabled: true